example/spotify_dart_example.dart
lib/spotify_browser.json.g.dart
lib/spotify_io.dart
lib/spotify_io.json.g.dart
lib/src/endpoints/endpoint_paging.dart
lib/src/endpoints/playlists.dart
lib/src/endpoints/users.dart
lib/src/models/paging.dart
lib/src/models/playlist.dart

I need to be able to get all pages of playlists for my application, so this adds generic pagination support to the library.
[`handlePageAndGetNext`](https://github.com/rinukkusu/spotify-dart/commit/102e890403eb1710343a6715c3eef2fef2e7d1f6#diff-d822f7be4e95853c3b06041b33b74074R79) for streaming pages feels kinda hacky to me.
I'd appreciate your input about how the paging API should work. :smile:

Add pagination support

---

.gitignore
lib/src/endpoints/artists.dart
lib/src/endpoints/users.dart
lib/src/models/player.dart
lib/src/spotify_base.dart

For implicit grant authorization you need to do it by directing the user to the webpage. After they log in you can obtain the access token but currently `spotify-dart` doesn't have a way to set this token. opening up the token to be explicitly set, lets us use a lot of endpoints that are specific to individual user spotify data like the /me endpoint. 
what's also kind of cool about this is when the implicit grant token expires the refresh token method will be called and then we still have client_credentials permissions.

add APIToken setter method to support implicit grant functionality

---

lib/src/endpoints/endpoint_paging.dart
lib/src/spotify_mock.dart
test/spotify_test.dart

- propagates `SpotifyException` when dealing with `BundledPage` response
- allows error provocation when using unit test

see issue #22

---

analysis_options.yaml
example/example.dart
lib/src/endpoints/artists.dart
lib/src/endpoints/categories.dart
lib/src/endpoints/endpoint_base.dart
lib/src/endpoints/endpoint_paging.dart
lib/src/endpoints/playlists.dart
lib/src/endpoints/search.dart
lib/src/endpoints/tracks.dart
lib/src/endpoints/users.dart
lib/src/models/_models.g.dart
lib/src/models/album.dart
lib/src/models/artist.dart
lib/src/models/audio_feature.dart
lib/src/models/category.dart
lib/src/models/error.dart
lib/src/models/external_objects.dart
lib/src/models/followers.dart
lib/src/models/image.dart
lib/src/models/paging.dart
lib/src/models/player.dart
lib/src/models/playlist.dart
lib/src/models/track.dart
lib/src/models/user.dart
lib/src/spotify_base.dart
lib/src/spotify_browser.dart
lib/src/spotify_io.dart
lib/src/spotify_mock.dart
pubspec.yaml
test/spotify_test.dart

If you go to this package's [Analysis tab](https://pub.dev/packages/spotify#-analysis-tab-) on pub.dev, there's a big list of health suggestions that could be easily addressed to improve the package's overall quality score.
Changes in this PR:
* Add [pedantic](https://pub.dev/packages/pedantic) as a dev dependency, since it's the go-to static analysis tool for Dart, used by Google and [over 1300 packages](https://pub.dev/packages?q=dependency%3Apedantic)
* Address roughly 200 issues that were discovered after implementing **pedantic**'s new linter rules
* Add `// ignore: unused_element` for 2 issues that don't seem like they need to be fixed
According to a local run of [pana](https://pub.dev/packages/pana#-readme-tab-), the tool used to generate package quality scores on pub.dev, these …

Improve static analysis health

---

README.md

This PR adds more details about Spotify authorization to the README based on the discussion in https://github.com/rinukkusu/spotify-dart/issues/37.
I've personally used every approach I mentioned for Flutter, but I'd appreciate any thoughts from @rinukkusu and @roisnir on how to better explain the Authorization Code Flow for a Dart app.

Add new authorization details to README

---

lib/spotify.dart
lib/src/spotify_mock.dart
test/spotify_test.dart

This PR will fix https://github.com/rinukkusu/spotify-dart/issues/42, an issue that was introduced with https://github.com/rinukkusu/spotify-dart/pull/34 (my bad).
I'm making two assumptions with these changes, please call me out if either are incorrect:
* There's no real reason that we need `spotify_mock.dart` to be part of the `spotify` library
* We don't actually need to import `dart:io` or `dart:html` in order for [`http.Client()` to know which type  of client to create](https://github.com/dart-lang/http/blob/master/lib/src/client.dart#L31-L35); it just detects which library is _available_, not which library is imported
Testing looks good run from running unit tests and debugging in a Flutter app. However, I haven't directly tested these changes against a web app yet, which is why …

Fix web compilation issues

---

lib/src/models/album.dart

We probably shouldn't have this odd way of detecting different "versions" of objects.
Fixes #39

Remove object type detection hack

---

lib/spotify.dart
lib/src/endpoints/me.dart
lib/src/endpoints/users.dart
lib/src/spotify_base.dart

I found the mix in the `Users` endpoint class a little confusing and decided to pull out all `me` related calls to its own endpoint class.

Move 'me' related calls to own endpoint class

---

CHANGELOG.md
lib/src/endpoints/search.dart
pubspec.yaml

This PR adds the parameter `market` to the search endpoint to be able to specifiy for which market to return search results.

Search: add market parameter

---

lib/src/endpoints/me.dart

Had a use case to fetch a user's following artists. Seems like the `/v1/me/following` endpoint requires a `type` param, which only supports `artist` right now ([doc here](https://developer.spotify.com/documentation/web-api/reference/follow/get-followed/)), so I kind of made the function specifically return artists right now. Open to generalizing/renaming function if needed.

Add /me/following endpoint

---

lib/src/endpoints/playlists.dart

Seems like the `addTrack` function for playlist only accepts one track. Didn't want to tweak the existing function so added an `addTracks` function that takes a list of strings (track URI).

Add support to add multiple tracks to a playlist

---

example/example.dart
lib/src/models/_models.g.dart
lib/src/models/album.dart

This PR adds `release_date` and `release_date_precision` to `AlbumSimple`.
Also prints these fields in the example to verify they are present.
Fixes #63

Add release date to AlbumSimple

---

README.md
example/example_auth.dart
lib/src/spotify_base.dart
lib/src/spotify_credentials.dart
test/spotify_test.dart

Changes:
* Support creating Spotify API from saved credentials, based off https://github.com/rinukkusu/spotify-dart/issues/32#issuecomment-619038947
* Simplify construction of a fully qualified `SpotifyApiCredentials` object
* Update README with directions on how to authenticate with saved credentials

Saved Credentials Authorization

---

lib/src/endpoints/me.dart
lib/src/endpoints/users.dart
lib/src/models/_models.g.dart
lib/src/models/user.dart

The `me.recentlyPlayed()` function now supports the `limit`, `before`, and `after` parameters that Spotify supports, and it returns `PlayHistory` objects, which retain the `playedAt` and `context` values.

Improved me.recentlyPlayed() (fixes #30)

---

lib/src/endpoints/me.dart
test/data/v1/me/player/recently.json
test/spotify_test.dart

This PR adds a unit test for the `recently-played` endpoint.
It also explicitly casts decoded json items to `PlayHistory`, which otherwise caused a runtime error.

Unit test for the recently-played endpoint

---

README.md
lib/src/spotify.dart
lib/src/spotify_base.dart

With this PR I've added the ability to get the new credentials obtained when the oAuth library updates them. This is usually the case when the app is open for a very long time and the previous access token is expired while I'm using the app. 
This also solves issue #86.
I've also added some lines in the readme file to notify new users about this feature.

Implemented credentials refresh callback

---

example/example_auth.dart
lib/src/endpoints/playlists.dart

This PR adds optional parameters `public`, `collaborative` and `description` (as stated in the API reference) to the createPlaylist function.
For testing purposes, I wrote an example call in example_auth.dart. You can uncomment [this line](https://github.com/rinukkusu/spotify-dart/compare/master...doodlezucc:master#diff-453b7c78bb316aac18630cae4a77d3edfb33bbd8912bf6eb65f53c1ee7d1da94R20) to try it out.

Additional createPlaylist parameters

---

lib/src/endpoints/me.dart
test/data/v1/me/shows.json
test/spotify_test.dart

This PR adds support for the user saved shows endpoint (`/me/shows`)
https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-users-saved-shows

Add support for user saved shows

---

.vscode/launch.json

This PR allows to launching to debug the `example_auth.dart` and `example.dart` accordingly with support of stdin.
It can be launched through this:

Add example_auth.dart into launch.json

---

lib/src/endpoints/shows.dart

The default empty value prevents `_buildQuery` (https://github.com/rinukkusu/spotify-dart/blob/master/lib/src/endpoints/shows.dart#L47) to properly filter the parameter (as _buildQuery only filter null values, not empty one).
I then get the following error when I try to get the episodes as an empty market parameter is sent to Spotify (instead of no market parameter)
```
Exception has occurred.
SpotifyException (Error Code: 400
Invalid market code)
```

[Fix] Remove default empty market when listing episodes

---

CHANGELOG.md
README.md
lib/src/spotify.dart
lib/src/spotify_base.dart
lib/src/spotify_credentials.dart

Addresses https://github.com/rinukkusu/spotify-dart/issues/70 by adding a new constructor that only requires a valid access token.

Create a client using only an AccessToken

---

lib/src/endpoints/playlists.dart

I have a use case where I want to add a track to a playlist at a specific location. 
By default, tracks are added to the end of the playlist. This PR adds an option "position" property property which, if provided, is appended to the URL sent to Spotify.

Add support to add a track to a playlist at the desired position.

---

lib/src/endpoints/me.dart
lib/src/endpoints/playlists.dart
lib/src/endpoints/tracks.dart
lib/src/spotify_base.dart
lib/src/spotify_mock.dart
test/data/v1/me/albums.json
test/data/v1/me/albums/contains.json
test/data/v1/me/following/contains.json
test/spotify_test.dart

Added support for following endpoints
| Endpoints                                      | Class    | Method           | HTTP method |
|------------------------------------------------|----------|------------------|-------------|
| /v1/me/following/contains                      | Me       | isFollowing      | GET         |
| /v1/me/following                               | Me       | follow           | PUT         |
| /v1/me/following                               | Me       | unfollow         | DELETE      |
| /v1/me/albums                                   | Me       | savedAlbums      | GET         |
| /v1/me/albums                                   | Me       | saveAlbums       | PUT         |
| /v1/me/albums                                   | Me       | removeAlbums     | DELETE …

User library & follow endpoint implementations

---

example/example_async.dart
lib/spotify.dart
lib/src/spotify.dart
lib/src/spotify_base.dart

Right now the only way to instantiate SpotifyApi class with credentials is like this:
```dart
var credentials = SpotifyApiCredentials(
'clientId',
'clientSecret',
);
var spotify = SpotifyApi(credentials);
```
But with wrong credentials you get AuthorizationException, which you can't catch with any obvious way (and probably can't catch without modifying the library itself at all)
```dart
try {
var spotify = SpotifyApi(invalidCredentials);
} on AuthorizationException {
print('This will never print despite the exception being thrown');
}
```
That is because `_getOauth2Client` method never gets awaited and is instantly used in class.
https://github.com/rinukkusu/spotify-dart/blob/7af8323ebe3831fac1ac8beb72aa5c991728f827/lib/src/spotify_base.dart#L54-L56
However, this PR allows instantiating …

Added static async factory to SpotifyApi to catch exceptions thrown by oauth2 package

---

example/example_auth.dart
lib/spotify.dart
lib/src/endpoints/me.dart
lib/src/endpoints/player.dart
lib/src/endpoints/users.dart
lib/src/spotify_base.dart
test/spotify_test.dart

This PR fixes #139. 
It furthermore depracates the following methods in `Me` as they have been moved to the new `PlayerEndpoint` class:
* `queue`
* `addToQueue`
* `devices`
* `player`
* `shuffle`

Refactors player methods from `me`

---

lib/spotify.dart
lib/src/endpoints/episodes.dart
lib/src/models/_models.g.dart
lib/src/models/copyright.dart
lib/src/models/episode.dart
lib/src/models/show.dart
lib/src/spotify_base.dart
test/data/v1/episodes/5Xt5DXGzch68nYYamXrNxZ.json
test/data/v1/me/episodes.json
test/spotify_test.dart

This PR adds the the episode api. Currently it consists of the the following endpoints:
* `getEpisode`
* `listEpisodes`
Furthermore a new class `EpisodeFull` has been created that contains the `show` as in the [response json](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-an-episode).

Adds episode API

---

lib/src/endpoints/me.dart
lib/src/endpoints/player.dart
lib/src/models/_models.dart
lib/src/models/_models.g.dart
lib/src/models/player.dart
test/data/v1/me/player.json
test/spotify_test.dart

This PR adds these player related endpoints:
- start or resume playback
- pause playback
- previous track
- next track
- seek to position in currently playing track
- repeat playback
- volume control
@hayribakici in the `shuffle` endpoint you're making another call to `playbackState` and returning that response and I was wondering, if you think we should do this for these methods, too? 🤔

Add player methods for controlling playback (#134)

---

lib/spotify.dart
lib/spotify_browser.dart
lib/spotify_io.dart
lib/src/endpoints/endpoint_paging.dart
lib/src/endpoints/me.dart
lib/src/endpoints/player.dart
lib/src/models/device.dart
lib/src/models/episode.dart
lib/src/models/paging.dart
lib/src/models/player.dart
lib/src/models/playlist.dart
lib/src/models/recommendations.dart
lib/src/models/track.dart

Adds library documentation and removes all warnings in order to make `dart doc` happy.
It also removes the deprecated files `spotify_io.dart` and `spotify_browser.dart` as they were the issue why `dart doc` throws errors.

Making `dart doc` happy

---

example/example_auth.dart
lib/src/endpoints/playlists.dart

This PR implements the `v1/playlists/$playlistId/tracks` endpoint, which allows reordering, replacing and clearing playlist items. 
This PR also implements a "fake" remove playlist method (see comments in code).

Update playlist items

---

README.md
example/example_auth.dart
lib/spotify.dart
lib/src/authorization_scope.dart
lib/src/endpoints/me.dart
lib/src/endpoints/search.dart
lib/src/spotify_base.dart
lib/src/spotify_credentials.dart
lib/src/utils.dart
test/spotify_mock.dart

This PR provides constants for the authorization scopes. With this, choosing the correct scope will be less error prone as it might happen that the user of this library makes spelling mistakes.
It also adds some refactoring with classes that contain a `key` property. I looked into it a little closer and the public `key` property should never be used outside of this library. Therefore it was removed.
I'm not 100% sure of this approach, dividing the scopes into different classes as they also could be fit into the `AuthorizationScope` class. What do you think?

Authorization scope

---

lib/src/authorization_scope.dart
lib/src/endpoints/endpoint_paging.dart
lib/src/endpoints/me.dart
lib/src/endpoints/playlists.dart
lib/src/endpoints/tracks.dart
test/data/v1/me/tracks/contains.json
test/data/v1/playlists/1XIAxOGAEK2h4ravpNTmYF/followers/contains.json
test/spotify_test.dart

This PR is a catch up regarding the return type `Map<String, bool>` of the `Me.isFollowing`, `TracksMe.contains` and `Playlist.followedBy` methods, which are now marked as deprecated and are replaced by `Me.containsFollowing`, `TracksMe.containsTracks` and `Playlist.followedByUsers`.

Add `Map<String, bool>` return type and method depracation

---

lib/src/endpoints/player.dart

This PR implements the `/transfer` endpoint resulting in transferring the playback into a given device id.

Implements `transfer` playback endpoint

---

lib/src/endpoints/me.dart
lib/src/endpoints/search.dart
lib/src/utils.dart

This PR replaces the `ExtendedEnum` class with dart's [enhanced enum](https://dart.dev/language/enum#declaring-enhanced-enums) concept resulting in less class overhead.

Replaces `ExtendedEnum` with dart's enhanced enum concept

---

analysis_options.yaml
lib/spotify.dart
lib/src/models/_models.g.dart
pubspec.yaml

This PR upgrades a few dependencies to more current versions.
Fixes #167

Upgrade Dependencies

---

lib/src/models/_models.g.dart
lib/src/models/device.dart
test/data/v1/me/player/devices.json
test/spotify_test.dart

This PR fixes #177 . 
Since the list of supported `DeviceType` values could not be found in the API documentation (e.g. `SmartWatch`), the library sets unknown enum values as `DeviceType.Unknown`.

Handling of unknown `DeviceType`s

---

lib/src/endpoints/playlists.dart

This PR fixes #179. As pointed out by @addreeh that playlist items also contain `episodes`. For a quick fix, this PR restricts the return types to `tracks`. A seperate issue to support both `episode`s and `track`s is documented in #181.

Restrict playlist return items to `tracks`

---

lib/src/endpoints/playlists.dart

Oopsiedaisy, forgot a `?` for the query in #182 .

Adds missing query start character

---

lib/src/endpoints/player.dart
lib/src/models/_models.g.dart
lib/src/models/player.dart

As discussed, this PR fixes #175 and depracates the method `startOrResume` by splitting its functionality into three new methods:
- `startWithTrackUris`, which starts a new context given a list of `Track` ids
- `startWithContext`, which starts a new context given a `contextUri`
- `resume`, which resumes a current playback

Refactor `playOrResume`

---

lib/src/endpoints/player.dart

Fixes #191. Returns an empty `PlaybackState` object if the response is empty.
@rinukkusu should rather maybe an error be returned instead? E.g.
```dart
Future<PlaybackState> playbackState([Market? market]) async {
var jsonString = await _api._get(...);
if (jsonString.isEmpty) {
return Future.error(SpotifyException('No playback context found'));
}
...
}
```

Catching empty response on `PlaybackState`

---

example/example_auth.dart
lib/src/models/player.dart

This PR fixes #202 as pointed out by @ILikeRubberDuckies. 
The bug arose, because the json contained an `offset` attribute, when it should be `null`. The `example_auth.dart` now contains testing methods to start playback by `trackIds` or `contextUris`.

Offset fix

---

example/example.dart
lib/src/spotify_base.dart
pubspec.yaml

This PR fixes #154 and adds a new method `spotifyApi.expandLink(shortenedUrl)` to expand shortened links.
In order that to happen the underlying http library has been updated to version `1.2.0`.

Expand shortened spotify url

---

lib/src/endpoints/player.dart
lib/src/models/_models.g.dart
lib/src/models/player.dart
test/data/v1/me/player/play.json
test/spotify_mock.dart
test/spotify_test.dart

Since the json attributes of the `PlayOrResumeOptions` must be disjointed, two new classes have been implemented to keep unnecessary attributes out of the request body. This is the consequence of #202. 
Furthermore, in order to test `PUT`, `POST` or `DELETE` http methods, a very rudiment interceptor has been added.

Refactor `PlayOrResumeOptions`

---

lib/src/spotify_api.dart
lib/src/spotify_base.dart

Expose `codeVerifier` when building `AuthorizationCodeGrant` from `SpotifyApi.authorizationCodeGrant`.
Issue: https://github.com/rinukkusu/spotify-dart/issues/201

`SpotifyApi.authorizationCodeGrant`: add parameter `codeVerifier`.

---

lib/src/models/_models.g.dart
lib/src/models/audio_analysis.dart
lib/src/models/audio_feature.dart
lib/src/models/device.dart
lib/src/models/episode.dart
lib/src/models/error.dart
lib/src/models/paging.dart
lib/src/models/player.dart
lib/src/models/recommendations.dart
lib/src/models/show.dart
lib/src/models/track.dart
lib/src/spotify_base.dart
lib/src/utils.dart

Extending @hayribakici fix, I applied the same `convertToInIfDoubleValue` for all `int` and `int?` type properties across the library just to be future-proof 😅  
Currently, it's happening for the following endpoints:
- album/tracks, 
- artists, (fixed + releases)
- artist, (fixed + releases)
- artist/related-artists (fixed + releases)

fix: spotify sending double instead of int for documented endpoints

---

lib/src/authorization_scope.dart

There's no `user-read-profile` in [spotify scopes](https://developer.spotify.com/documentation/web-api/concepts/scopes) so `illegal scope` is fired during authorization.
Now we can fetch user information like market, product (free, premium), and email.

replace user-read-profile with user-read-private in AuthorizationScope

---

lib/src/models/_models.g.dart
lib/src/models/album.dart
lib/src/models/artist.dart
lib/src/models/audio_analysis.dart
lib/src/models/audio_feature.dart
lib/src/models/category.dart
lib/src/models/copyright.dart
lib/src/models/device.dart
lib/src/models/episode.dart
lib/src/models/error.dart
lib/src/models/external_objects.dart
lib/src/models/followers.dart
lib/src/models/image.dart
lib/src/models/paging.dart
lib/src/models/player.dart
lib/src/models/playlist.dart
lib/src/models/queue.dart
lib/src/models/recommendations.dart
lib/src/models/show.dart
lib/src/models/track.dart
lib/src/models/user.dart

feat: enable to json for every serializable model
