rinukkusu/spotify-dart

.gitignore
analysis_options.yaml
lib/src/endpoints/endpoint_paging.dart
lib/src/endpoints/playlists.dart
pubspec.yaml

- playlists
- added addTrack
- added createPlaylist
- me bugfix (Playlist -> PlaylistSimple)
- paging bugfix

Add addTrack and createPlaylist to playlists endpoint

---

README.md

This PR updates README on how to run the example with the authentication flow.

Updates documentation for example with authentication flow

---

lib/src/endpoints/audio_features.dart

json key => audio-features updated to audio_features
#45

spotify api parsing issue fixed

---

lib/src/endpoints/endpoint_paging.dart

This little bug fix slipped away from #43, sorry for that.

fixed fromPaging bug

---

lib/src/endpoints/artists.dart

Didn't find any previous tests for paged endpoints so didn't add tests for this. Please let me know if I missed anything :)

Adds artists.albums(artistId) to fetch album pages for artist

---

lib/src/endpoints/playlists.dart
lib/src/models/album.dart

Adds new endpoints for following and unfollowing playlists.

Follow and unfollow playlists

---

lib/src/endpoints/me.dart

Adds new endpoint for Top Artists.

Added Top Artists

---

lib/src/endpoints/tracks.dart
lib/src/models/_models.dart
lib/src/models/_models.g.dart
lib/src/models/album.dart
test/spotify_test.dart

This PR adds tracks into the album model and solves the issue #82.

Adds tracks list in album. #82

---

lib/src/models/_models.g.dart
lib/src/models/album.dart
test/spotify_test.dart

This PR fixes #84 and removes the unnecessary fields of `Album`.

Removes unnecessary overriden fields of Album

---

lib/src/models/_models.g.dart
lib/src/models/playlist.dart
test/data/v1/search.json

Add playlist description field

---

README.md
lib/src/endpoints/playlists.dart

* Added the ability to update a playlist's information
* Added the ability to upload a custom image for a playlist
* Updated documentation for server-side authentication flow and how to refresh a token in this scenario (thanks @[mitchhymel](https://github.com/mitchhymel) for the snippet)

Playlist additions and documentation updates

---

lib/src/endpoints/endpoint_paging.dart
lib/src/models/_models.g.dart
lib/src/models/paging.dart

Make limit and total null-safe in paging

---

lib/src/endpoints/endpoint_paging.dart
lib/src/models/_models.g.dart
lib/src/models/paging.dart

* paging.dart: make limit and total null-safe.

Make limit and total null-safe in paging (#126)

---

example/example.dart
example/example_auth.dart
lib/src/endpoints/playlists.dart
test/data/v1/users/X123Y/playlists.json
test/spotify_test.dart

This PR implements the `users/{userId}/playlists` endpoint.

`users/id/playlists` endpoint

---

lib/src/endpoints/me.dart
lib/src/models/_models.dart
lib/src/models/_models.g.dart
lib/src/models/queue.dart
test/data/v1/me/player/queue.json
test/spotify_test.dart

Hey there!
I'm looking to add this to a personal project, so I quickly added these methods and some tests.  
Let me know if you need me to change something. Thanks.

Added queue endpoints

---

example/example.dart
example/example_auth.dart
lib/src/endpoints/endpoint_paging.dart
lib/src/endpoints/me.dart
lib/src/endpoints/recommendations.dart
lib/src/endpoints/search.dart
lib/src/models/album.dart
lib/src/models/show.dart
lib/src/spotify_credentials.dart
test/spotify_test.dart

This PR fixes all of the static analysis errors we got while trying to publish the package to pub.dev, since the new Dart SDK came out.
Some (unused) code and methods have been removed, some parameters had their nullability changed.

Fix warnings from static analysis

---

example/example_auth.dart
lib/src/endpoints/me.dart
test/data/v1/me/episodes.json
test/data/v1/me/episodes/contains.json
test/spotify_test.dart

This PR implements the `me/episodes` api calls.
Furthermore, it organizes the tests a little bit.

Implements `me/episodes` api calls

---

lib/src/endpoints/playlists.dart
test/data/v1/playlists/1XIAxOGAEK2h4ravpNTmYF/images.json
test/spotify_test.dart

This PR implements the `v1/playlists/<id>/image` endpoint.

implements retrieval of images of a playlist

---

lib/src/endpoints/player.dart
lib/src/spotify_base.dart

This PR fixes https://github.com/rinukkusu/spotify-dart/issues/185.

fix malformed json error in startOrResume

---

build.yaml
lib/src/models/_models.g.dart
lib/src/models/album.dart

Context: https://github.com/rinukkusu/spotify-dart/pull/213#issuecomment-2081326383

fix: toJson not called on child properties explicitly

---

lib/src/endpoints/endpoint_paging.dart
lib/src/endpoints/playlists.dart
test/data/v1/playlists/1XIAxOGAEK2h4ravpNTmYF/tracks.json
test/spotify_test.dart

This PR is a followup to the discussion in #218. It follows the second approach described there that uses a filter function instead of returning nullable track objects.
I decided to create a 2nd PR so both approaches can be discussed and evaluated before a decision will be made.

Add filter function to pagination logic and use it in playlists

---

lib/src/endpoints/endpoint_base.dart
test/data/v1/audio-features.json
test/data/v1/audio-features/11dFghVXANMlKmJXsNCbNl.json
test/data/v1/audio-features/2cs7JxrZ9DxvsfoVI07ayX.json
test/spotify_test.dart

Fixes #223  incorrect json returned from spotify for some audio features
https://api.spotify.com/v1/audio-features?ids=2cs7JxrZ9DxvsfoVI07ayX return
```
{
"audio_features": [
null
]
}
```

add null check before fromJson to endpoint_base.dart
